In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
%matplotlib inline
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_excel('data_preprocessing.xlsx')
data.head()

Dept   Age Experience   Salary       Education  Projects
0   HR  32.0          9  40000.0  Under_Graduate       0.0
1   HR  33.0         12  48000.0          Master       0.0
2   IT  35.0         12  45000.0          Master       5.0
3   IT   NaN         12  46000.0        Graduate       5.0
4   HR  34.0         11      NaN        Graduate       2.0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Dept        31 non-null     object 
 1   Age         30 non-null     float64
 2   Experience  29 non-null     object 
 3   Salary      31 non-null     float64
 4   Education   31 non-null     object 
 5   Projects    27 non-null     float64
dtypes: float64(3), object(3)
memory usage: 1.7+ KB


In [4]:
data['Salary'].isna().sum()

2

In [5]:
data.shape

(33, 6)

In [6]:
data['Dept'].unique()

array(['HR', 'IT', 'Marketing', 'Sales', nan], dtype=object)

In [7]:
data['Experience'].unique()

array([9, 12, 11, 13, 10, nan, 14, 8.5, 2, 35, '.', '%', 'a', 45, 0, 50],
      dtype=object)

In [8]:
data['Salary'].unique()

array([40000., 48000., 45000., 46000.,    nan, 42000., 39000., 36000.,
       45500., 38000., 35000., 32000., 22000., 60000., 23000., 26000.,
       90000., 88000., 20000.])

In [9]:
data['Education'].unique()

array(['Under_Graduate', 'Master', 'Graduate', nan, 'a', '?'],
      dtype=object)

In [10]:
data['Projects'].unique()

array([ 0.,  5.,  2.,  1., nan,  3.])

In [11]:
data

Dept   Age Experience   Salary       Education  Projects
0          HR  32.0          9  40000.0  Under_Graduate       0.0
1          HR  33.0         12  48000.0          Master       0.0
2          IT  35.0         12  45000.0          Master       5.0
3          IT   NaN         12  46000.0        Graduate       5.0
4          HR  34.0         11      NaN        Graduate       2.0
5          IT  33.0         13  42000.0             NaN       1.0
6   Marketing  56.0         12  39000.0          Master       NaN
7          HR   NaN         10  42000.0          Master       NaN
8   Marketing  31.0        NaN  36000.0  Under_Graduate       2.0
9          IT  45.0         14      NaN          Master       3.0
10      Sales  50.0        NaN  46000.0          Master       3.0
11        NaN  75.0         14  45500.0        Graduate       3.0
12        NaN  29.0        8.5  38000.0             NaN       3.0
13         HR  32.0         11  39000.0  Under_Graduate       NaN
14      Sales  38.0        NaN  35000.0          Master       NaN
15         HR   0.0        NaN  32000.0  Under_Graduate       3.0
16         IT  42.0         14  42000.0        Graduate       3.0
17  Marketing  50.0         13  39000.0          Master       3.0
18         HR  38.0         11  42000.0        Graduate       2.0
19         HR   0.0          2  22000.0  Under_Graduate       2.0
20         IT  52.0         35  60000.0          Master       3.0
21      Sales  27.0          2  23000.0  Under_Graduate       1.0
22         HR  42.0         12  45000.0        Graduate       2.0
23         HR   0.0          2  22000.0  Under_Graduate       1.0
24         IT  51.0          .  60000.0          Master       1.0
25      Sales  28.0          2  23000.0               a       1.0
26      Sales  29.0          %  26000.0  Under_Graduate       3.0
27         HR  42.0          a  45000.0        Graduate       NaN
28      Sales  70.0         45  90000.0          Master       NaN
29         HR  32.0         12  88000.0  Under_Graduate       1.0
30         IT  19.0          0  20000.0        Graduate       2.0
31  Marketing  75.0         50  39000.0          Master       1.0
32         HR   NaN         11  42000.0               ?       2.0

In [28]:
missing_values = ['.','%','a','?','NaN']
new_data = pd.read_excel('data_preprocessing.xlsx', na_values=missing_values)
data1 = new_data.copy()


In [29]:
data1

Dept   Age  Experience   Salary       Education  Projects
0          HR  32.0         9.0  40000.0  Under_Graduate       0.0
1          HR  33.0        12.0  48000.0          Master       0.0
2          IT  35.0        12.0  45000.0          Master       5.0
3          IT   NaN        12.0  46000.0        Graduate       5.0
4          HR  34.0        11.0      NaN        Graduate       2.0
5          IT  33.0        13.0  42000.0             NaN       1.0
6   Marketing  56.0        12.0  39000.0          Master       NaN
7          HR   NaN        10.0  42000.0          Master       NaN
8   Marketing  31.0         NaN  36000.0  Under_Graduate       2.0
9          IT  45.0        14.0      NaN          Master       3.0
10      Sales  50.0         NaN  46000.0          Master       3.0
11        NaN  75.0        14.0  45500.0        Graduate       3.0
12        NaN  29.0         8.5  38000.0             NaN       3.0
13         HR  32.0        11.0  39000.0  Under_Graduate       NaN
14      Sales  38.0         NaN  35000.0          Master       NaN
15         HR   0.0         NaN  32000.0  Under_Graduate       3.0
16         IT  42.0        14.0  42000.0        Graduate       3.0
17  Marketing  50.0        13.0  39000.0          Master       3.0
18         HR  38.0        11.0  42000.0        Graduate       2.0
19         HR   0.0         2.0  22000.0  Under_Graduate       2.0
20         IT  52.0        35.0  60000.0          Master       3.0
21      Sales  27.0         2.0  23000.0  Under_Graduate       1.0
22         HR  42.0        12.0  45000.0        Graduate       2.0
23         HR   0.0         2.0  22000.0  Under_Graduate       1.0
24         IT  51.0         NaN  60000.0          Master       1.0
25      Sales  28.0         2.0  23000.0             NaN       1.0
26      Sales  29.0         NaN  26000.0  Under_Graduate       3.0
27         HR  42.0         NaN  45000.0        Graduate       NaN
28      Sales  70.0        45.0  90000.0          Master       NaN
29         HR  32.0        12.0  88000.0  Under_Graduate       1.0
30         IT  19.0         0.0  20000.0        Graduate       2.0
31  Marketing  75.0        50.0  39000.0          Master       1.0
32         HR   NaN        11.0  42000.0             NaN       2.0

In [30]:
m_Age = (data1['Age'].median())
m_Age

34.5

In [31]:
print(data1['Age'].unique())
data1['Age'].fillna(value = data1['Age'].median(), inplace = True)
data1['Age'].replace(to_replace=0.0, value =  data1['Age'].median(), inplace = True )

[32. 33. 35. nan 34. 56. 31. 45. 50. 75. 29. 38.  0. 42. 52. 27. 51. 28.
 70. 19.]


In [32]:
print(data1['Salary'].unique())
data1['Salary'].fillna(value = data1['Salary'].median(), inplace = True)


[40000. 48000. 45000. 46000.    nan 42000. 39000. 36000. 45500. 38000.
 35000. 32000. 22000. 60000. 23000. 26000. 90000. 88000. 20000.]


In [33]:
print(data1['Experience'].unique())
data1['Experience'].fillna(value = data1['Experience'].median(), inplace = True)

[ 9.  12.  11.  13.  10.   nan 14.   8.5  2.  35.  45.   0.  50. ]


In [34]:
print(data1['Dept'].unique())


['HR' 'IT' 'Marketing' 'Sales' nan]


In [35]:
data1['Dept'].value_counts()

HR           13
IT            8
Sales         6
Marketing     4
Name: Dept, dtype: int64

In [36]:
print(data1['Education'].unique())
condition = data1['Salary']<30000.0
data1['Education'] = data1['Education'].fillna(condition.map({True:'Under_Graduate', False:'Master'}))

['Under_Graduate' 'Master' 'Graduate' nan]


In [37]:
print(data1['Education'].unique())

['Under_Graduate' 'Master' 'Graduate']


In [38]:
print(data1['Projects'].unique())
data1['Projects'].fillna(value = data1['Projects'].median(), inplace = True)

[ 0.  5.  2.  1. nan  3.]


In [39]:
data1

Dept   Age  Experience   Salary       Education  Projects
0          HR  32.0         9.0  40000.0  Under_Graduate       0.0
1          HR  33.0        12.0  48000.0          Master       0.0
2          IT  35.0        12.0  45000.0          Master       5.0
3          IT  34.5        12.0  46000.0        Graduate       5.0
4          HR  34.0        11.0  42000.0        Graduate       2.0
5          IT  33.0        13.0  42000.0          Master       1.0
6   Marketing  56.0        12.0  39000.0          Master       2.0
7          HR  34.5        10.0  42000.0          Master       2.0
8   Marketing  31.0        12.0  36000.0  Under_Graduate       2.0
9          IT  45.0        14.0  42000.0          Master       3.0
10      Sales  50.0        12.0  46000.0          Master       3.0
11        NaN  75.0        14.0  45500.0        Graduate       3.0
12        NaN  29.0         8.5  38000.0          Master       3.0
13         HR  32.0        11.0  39000.0  Under_Graduate       2.0
14      Sales  38.0        12.0  35000.0          Master       2.0
15         HR  34.5        12.0  32000.0  Under_Graduate       3.0
16         IT  42.0        14.0  42000.0        Graduate       3.0
17  Marketing  50.0        13.0  39000.0          Master       3.0
18         HR  38.0        11.0  42000.0        Graduate       2.0
19         HR  34.5         2.0  22000.0  Under_Graduate       2.0
20         IT  52.0        35.0  60000.0          Master       3.0
21      Sales  27.0         2.0  23000.0  Under_Graduate       1.0
22         HR  42.0        12.0  45000.0        Graduate       2.0
23         HR  34.5         2.0  22000.0  Under_Graduate       1.0
24         IT  51.0        12.0  60000.0          Master       1.0
25      Sales  28.0         2.0  23000.0  Under_Graduate       1.0
26      Sales  29.0        12.0  26000.0  Under_Graduate       3.0
27         HR  42.0        12.0  45000.0        Graduate       2.0
28      Sales  70.0        45.0  90000.0          Master       2.0
29         HR  32.0        12.0  88000.0  Under_Graduate       1.0
30         IT  19.0         0.0  20000.0        Graduate       2.0
31  Marketing  75.0        50.0  39000.0          Master       1.0
32         HR  34.5        11.0  42000.0          Master       2.0

In [40]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Dept        31 non-null     object 
 1   Age         33 non-null     float64
 2   Experience  33 non-null     float64
 3   Salary      33 non-null     float64
 4   Education   33 non-null     object 
 5   Projects    33 non-null     float64
dtypes: float64(4), object(2)
memory usage: 1.7+ KB


In [41]:
data1.describe()

Age  Experience        Salary   Projects
count  33.000000   33.000000     33.000000  33.000000
mean   40.212121   13.136364  41984.848485   2.121212
std    13.374434   10.616374  15490.160611   1.139012
min    19.000000    0.000000  20000.000000   0.000000
25%    32.000000   11.000000  36000.000000   1.000000
50%    34.500000   12.000000  42000.000000   2.000000
75%    45.000000   12.000000  45000.000000   3.000000
max    75.000000   50.000000  90000.000000   5.000000

In [42]:
pip install nbconvert