https://pandas.pydata.org/

In [1]:
import pandas as pd

In [2]:
# Series
# 1D array like data type containing sequence of values

In [3]:
s1 = pd.Series([10, 20, 30, 40, 50])

In [4]:
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [5]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
type(s1)

pandas.core.series.Series

In [7]:
val1 = s1.values

In [8]:
print(val1)

[10 20 30 40 50]


In [9]:
val1

array([10, 20, 30, 40, 50], dtype=int64)

In [10]:
type(val1)

numpy.ndarray

In [11]:
val1.ndim

1

In [12]:
val1.shape

(5,)

In [13]:
val1.dtype

dtype('int64')

In [14]:
val1.size

5

In [15]:
i1 = s1.index

In [16]:
i1

RangeIndex(start=0, stop=5, step=1)

In [17]:
type(i1)

pandas.core.indexes.range.RangeIndex

In [18]:
import numpy as np

In [19]:
arr1 = np.array([10, 20, 30, 40, 50])
s2 = pd.Series(arr1, index=['a', 'b', 'c', 'd', 'e'])

In [20]:
s2

a    10
b    20
c    30
d    40
e    50
dtype: int32

In [21]:
val2 = s2.values

In [22]:
val2

array([10, 20, 30, 40, 50])

In [23]:
i2 = s2.index

In [24]:
i2

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [25]:
type(i2)

pandas.core.indexes.base.Index

In [26]:
print(val2)

[10 20 30 40 50]


In [27]:
s2

a    10
b    20
c    30
d    40
e    50
dtype: int32

In [28]:
s2['a']

10

In [29]:
s2['e']

50

In [30]:
s2['z']

KeyError: 'z'

In [31]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [32]:
s1[0]

10

In [33]:
s2

a    10
b    20
c    30
d    40
e    50
dtype: int32

In [34]:
s2[0]

10

In [35]:
s3 = pd.Series(arr1, index=[1,2,3,4,5])

In [36]:
s3

1    10
2    20
3    30
4    40
5    50
dtype: int32

In [37]:
s3[2]

20

In [38]:
s3[0]

KeyError: 0

In [39]:
s3

1    10
2    20
3    30
4    40
5    50
dtype: int32

In [40]:
s3.iloc[0]

10

In [41]:
s3.iloc[1]

20

In [42]:
s3.loc[1]

10

In [43]:
s2

a    10
b    20
c    30
d    40
e    50
dtype: int32

In [44]:
s2.loc['d']

40

In [45]:
s2.iloc[3]

40

In [46]:
s4 = pd.Series(arr1, index=['a', 'b', 'c', 'a', 'd'])

In [47]:
s4

a    10
b    20
c    30
a    40
d    50
dtype: int32

In [48]:
# Labels can be duplicate

In [49]:
s4['a']

a    10
a    40
dtype: int32

In [50]:
type(s4['a'])

pandas.core.series.Series

In [51]:
s5 = pd.Series(arr1, index=['a', 'b', 'c', 'd'])

ValueError: Length of values (5) does not match length of index (4)

In [52]:
s5  = pd.Series([10, 20, 'Mark', 30, 40])

In [53]:
s5

0      10
1      20
2    Mark
3      30
4      40
dtype: object

In [54]:
s5.values

array([10, 20, 'Mark', 30, 40], dtype=object)

In [55]:
arr2 = np.array([10, 20, 'Mark', 30, 40])

In [56]:
arr2

array(['10', '20', 'Mark', '30', '40'], dtype='<U11')

In [57]:
arr3 = np.array(['Python is fun', 'Python', 'Mark'])

In [58]:
arr3

array(['Python is fun', 'Python', 'Mark'], dtype='<U13')

In [59]:
s4

a    10
b    20
c    30
a    40
d    50
dtype: int32

In [60]:
s4['a']

a    10
a    40
dtype: int32

In [62]:
s4['b']

20

In [63]:
s4[['b', 'c']]

b    20
c    30
dtype: int32

In [64]:
s4

a    10
b    20
c    30
a    40
d    50
dtype: int32

In [65]:
s4['b'] = 100

In [66]:
s4

a     10
b    100
c     30
a     40
d     50
dtype: int32

In [67]:
s4['a'] = -1

In [68]:
s4

a     -1
b    100
c     30
a     -1
d     50
dtype: int32

In [69]:
s4.iloc[0] = 500

In [70]:
s4

a    500
b    100
c     30
a     -1
d     50
dtype: int32

In [74]:
s4.value_counts()

 500    1
 100    1
 30     1
-1      1
 50     1
dtype: int64

In [75]:
s4

a    500
b    100
c     30
a     -1
d     50
dtype: int32

In [76]:
s4['a'] = (2,3)

In [77]:
s4

a      2
b    100
c     30
a      3
d     50
dtype: int32

In [78]:
s4 + 1

a      3
b    101
c     31
a      4
d     51
dtype: int32

In [79]:
s4

a      2
b    100
c     30
a      3
d     50
dtype: int32

In [80]:
s5

0      10
1      20
2    Mark
3      30
4      40
dtype: object

In [81]:
s5 + 1

TypeError: can only concatenate str (not "int") to str

In [82]:
s4 * 2

a      4
b    200
c     60
a      6
d    100
dtype: int32

In [83]:
s5

0      10
1      20
2    Mark
3      30
4      40
dtype: object

In [84]:
s5 * 2

0          20
1          40
2    MarkMark
3          60
4          80
dtype: object

In [85]:
s4

a      2
b    100
c     30
a      3
d     50
dtype: int32

In [86]:
s4 >= 50

a    False
b     True
c    False
a    False
d     True
dtype: bool

In [87]:
s4[s4 >= 50]

b    100
d     50
dtype: int32

In [88]:
s4

a      2
b    100
c     30
a      3
d     50
dtype: int32

In [89]:
s4[s4<5]

a    2
a    3
dtype: int32

In [90]:
data = {'IN': 5.5, 'US': 3.0, 'UK': 1.5, 'AU': 7.4}

In [91]:
data

{'IN': 5.5, 'US': 3.0, 'UK': 1.5, 'AU': 7.4}

In [92]:
ser1 = pd.Series(data)

In [93]:
ser1

IN    5.5
US    3.0
UK    1.5
AU    7.4
dtype: float64

In [94]:
ser2 = pd.Series(data, index=['IN', 'CH', 'US', 'UK'])

In [95]:
ser2

IN    5.5
CH    NaN
US    3.0
UK    1.5
dtype: float64

In [96]:
ser2['CH']

nan

In [97]:
type(ser2['CH'])

numpy.float64

In [98]:
data = {'IN': 6.5, 'US': 2.0, 'UK': 2.5, 'AU': 6.4}

In [99]:
ser3 = pd.Series(data)

In [100]:
ser1

IN    5.5
US    3.0
UK    1.5
AU    7.4
dtype: float64

In [101]:
ser3

IN    6.5
US    2.0
UK    2.5
AU    6.4
dtype: float64

In [102]:
ser1 == ser3

IN    False
US    False
UK    False
AU    False
dtype: bool

In [103]:
ser1 > ser3

IN    False
US     True
UK    False
AU     True
dtype: bool

In [105]:
ser1 < ser3

IN     True
US    False
UK     True
AU    False
dtype: bool

In [107]:
ser1 + ser3

IN    12.0
US     5.0
UK     4.0
AU    13.8
dtype: float64

In [108]:
ser1

IN    5.5
US    3.0
UK    1.5
AU    7.4
dtype: float64

In [109]:
ser2

IN    5.5
CH    NaN
US    3.0
UK    1.5
dtype: float64

In [110]:
ser1 > ser2

ValueError: Can only compare identically-labeled Series objects

In [111]:
ser1 + ser2

AU     NaN
CH     NaN
IN    11.0
UK     3.0
US     6.0
dtype: float64

In [112]:
ser1 == ser2

ValueError: Can only compare identically-labeled Series objects

In [113]:
ser2

IN    5.5
CH    NaN
US    3.0
UK    1.5
dtype: float64

In [114]:
ser2.isna()

IN    False
CH     True
US    False
UK    False
dtype: bool

In [115]:
ser2.notna()

IN     True
CH    False
US     True
UK     True
dtype: bool

In [116]:
ser1

IN    5.5
US    3.0
UK    1.5
AU    7.4
dtype: float64

In [118]:
print(ser1.name)

None


In [121]:
ser1.name = 'GDP'

In [122]:
ser1

IN    5.5
US    3.0
UK    1.5
AU    7.4
Name: GDP, dtype: float64

In [123]:
ser4 = pd.Series(data, name='gdp')

In [124]:
ser4

IN    6.5
US    2.0
UK    2.5
AU    6.4
Name: gdp, dtype: float64

In [125]:
ser4.index = ['Ind', 'USA', 'UK', 'AUS']

In [126]:
ser4

Ind    6.5
USA    2.0
UK     2.5
AUS    6.4
Name: gdp, dtype: float64

In [127]:
ser4.name

'gdp'

In [128]:
ser4['UK'] = 2.7

In [129]:
ser4

Ind    6.5
USA    2.0
UK     2.7
AUS    6.4
Name: gdp, dtype: float64

In [130]:
ser4.loc['UK'] = 2.8

In [131]:
ser4

Ind    6.5
USA    2.0
UK     2.8
AUS    6.4
Name: gdp, dtype: float64

In [132]:
ser4.index

Index(['Ind', 'USA', 'UK', 'AUS'], dtype='object')

In [133]:
ser4.index[0]

'Ind'

In [134]:
ser4.index[0] = 'IND'

TypeError: Index does not support mutable operations

In [135]:
ser4

Ind    6.5
USA    2.0
UK     2.8
AUS    6.4
Name: gdp, dtype: float64

In [136]:
ser4.sort_index()

AUS    6.4
Ind    6.5
UK     2.8
USA    2.0
Name: gdp, dtype: float64

In [137]:
ser4.sort_index(ascending=False)

USA    2.0
UK     2.8
Ind    6.5
AUS    6.4
Name: gdp, dtype: float64

In [138]:
ser4

Ind    6.5
USA    2.0
UK     2.8
AUS    6.4
Name: gdp, dtype: float64

In [139]:
ser4

Ind    6.5
USA    2.0
UK     2.8
AUS    6.4
Name: gdp, dtype: float64

In [140]:
ser4.sort_values()

USA    2.0
UK     2.8
AUS    6.4
Ind    6.5
Name: gdp, dtype: float64

In [141]:
ser4.sort_values(ascending=False)

Ind    6.5
AUS    6.4
UK     2.8
USA    2.0
Name: gdp, dtype: float64

In [142]:
## Dataframe
# represents tabular data - rows and columns

In [143]:
data = {'names': ['Alice', 'John', 'Mark', 'Carol'],
       'ids': [101, 102, 103, 104],
       'percents': [78.5, 87.5, 68.0, 91.5]}

In [144]:
data

{'names': ['Alice', 'John', 'Mark', 'Carol'],
 'ids': [101, 102, 103, 104],
 'percents': [78.5, 87.5, 68.0, 91.5]}

In [145]:
stu_df = pd.DataFrame(data)

In [146]:
stu_df

names  ids  percents
0  Alice  101      78.5
1   John  102      87.5
2   Mark  103      68.0
3  Carol  104      91.5

In [147]:
stu_df.columns

Index(['names', 'ids', 'percents'], dtype='object')

In [148]:
type(stu_df.columns)

pandas.core.indexes.base.Index

In [149]:
stu_df.index

RangeIndex(start=0, stop=4, step=1)

In [150]:
stu_df.values

array([['Alice', 101, 78.5],
       ['John', 102, 87.5],
       ['Mark', 103, 68.0],
       ['Carol', 104, 91.5]], dtype=object)

In [151]:
stu_df

names  ids  percents
0  Alice  101      78.5
1   John  102      87.5
2   Mark  103      68.0
3  Carol  104      91.5

In [152]:
stu_df.loc[0]

names       Alice
ids           101
percents     78.5
Name: 0, dtype: object

In [153]:
stu_df[0]

KeyError: 0

In [154]:
stu_df['names']

0    Alice
1     John
2     Mark
3    Carol
Name: names, dtype: object

In [155]:
stu_df

names  ids  percents
0  Alice  101      78.5
1   John  102      87.5
2   Mark  103      68.0
3  Carol  104      91.5

In [156]:
stu_df['ids'][0]

101

In [157]:
stu_df['ids']

0    101
1    102
2    103
3    104
Name: ids, dtype: int64

In [158]:
stu_df['ids'].loc[0]

101

In [159]:
stu_df['ids'].iloc[0]

101

In [160]:
stu_df.loc[0]

names       Alice
ids           101
percents     78.5
Name: 0, dtype: object

In [161]:
stu_df.loc[0].loc['ids']

101

In [162]:
stu_df.loc[0]['ids']

101

In [163]:
stu_df[0]['ids']

KeyError: 0

In [164]:
stu_df.loc[0,'ids']

101

In [165]:
stu_df

names  ids  percents
0  Alice  101      78.5
1   John  102      87.5
2   Mark  103      68.0
3  Carol  104      91.5

In [166]:
stu_df['ids'].loc[0]

101

In [167]:
stu_df['ids'][0]

101

In [168]:
stu_df['ids']

0    101
1    102
2    103
3    104
Name: ids, dtype: int64

In [169]:
stu_df = pd.DataFrame(data, index=[10, 20, 30, 40])

In [170]:
stu_df

names  ids  percents
10  Alice  101      78.5
20   John  102      87.5
30   Mark  103      68.0
40  Carol  104      91.5

In [171]:
stu_df['ids'][10]

101

In [172]:
stu_df['ids'][0]

KeyError: 0

In [174]:
stu_df['ids'].iloc[0]

101

In [176]:
data

{'names': ['Alice', 'John', 'Mark', 'Carol'],
 'ids': [101, 102, 103, 104],
 'percents': [78.5, 87.5, 68.0, 91.5]}

In [177]:
df = pd.DataFrame(data, columns=['ids', 'names', 'percents'])

In [178]:
df

ids  names  percents
0  101  Alice      78.5
1  102   John      87.5
2  103   Mark      68.0
3  104  Carol      91.5

In [179]:
df = pd.DataFrame(data, columns=['ids', 'names', 'grades'])

In [180]:
df

ids  names grades
0  101  Alice    NaN
1  102   John    NaN
2  103   Mark    NaN
3  104  Carol    NaN

In [181]:
df = pd.DataFrame(data, columns=['ids', 'names', 'percents', 'grades'])

In [182]:
df

ids  names  percents grades
0  101  Alice      78.5    NaN
1  102   John      87.5    NaN
2  103   Mark      68.0    NaN
3  104  Carol      91.5    NaN

In [183]:
df.columns

Index(['ids', 'names', 'percents', 'grades'], dtype='object')

In [184]:
df.index = ['a', 'b', 'c', 'd']

In [185]:
df

ids  names  percents grades
a  101  Alice      78.5    NaN
b  102   John      87.5    NaN
c  103   Mark      68.0    NaN
d  104  Carol      91.5    NaN

In [186]:
df['grades']

a    NaN
b    NaN
c    NaN
d    NaN
Name: grades, dtype: object

In [187]:
df['grades'] = 'A'

In [188]:
df

ids  names  percents grades
a  101  Alice      78.5      A
b  102   John      87.5      A
c  103   Mark      68.0      A
d  104  Carol      91.5      A

In [189]:
df['grades'] = ['C', 'B', 'D', 'A']

In [190]:
df

ids  names  percents grades
a  101  Alice      78.5      C
b  102   John      87.5      B
c  103   Mark      68.0      D
d  104  Carol      91.5      A

In [191]:
df['col1'] = 1

In [192]:
df

ids  names  percents grades  col1
a  101  Alice      78.5      C     1
b  102   John      87.5      B     1
c  103   Mark      68.0      D     1
d  104  Carol      91.5      A     1

In [193]:
df['col2'] = np.arange(4)

In [194]:
df

ids  names  percents grades  col1  col2
a  101  Alice      78.5      C     1     0
b  102   John      87.5      B     1     1
c  103   Mark      68.0      D     1     2
d  104  Carol      91.5      A     1     3

In [195]:
df['col3'] = np.arange(5)

ValueError: Length of values (5) does not match length of index (4)

In [196]:
df

ids  names  percents grades  col1  col2
a  101  Alice      78.5      C     1     0
b  102   John      87.5      B     1     1
c  103   Mark      68.0      D     1     2
d  104  Carol      91.5      A     1     3

In [197]:
df.drop(['col1', 'col2'])

KeyError: "['col1' 'col2'] not found in axis"

In [198]:
help(df.drop)

Help on method drop in module pandas.core.frame:

drop(labels=None, axis: 'Axis' = 0, index=None, columns=None, level: 'Level | None' = None, inplace: 'bool' = False, errors: 'str' = 'raise') method of pandas.core.frame.DataFrame instance
    Drop specified labels from rows or columns.
    
    Remove rows or columns by specifying label names and corresponding
    axis, or by specifying directly index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level. See the `user guide <advanced.shown_levels>`
    for more information about the now unused levels.
    
    Parameters
    ----------
    labels : single label or list-like
        Index or column labels to drop.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index') or
        columns (1 or 'columns').
    index : single label or list-like
        Alternative to specifying axis (``labels, axis=0``
        is equiv

In [199]:
df.drop(['col1', 'col2'], axis=1)

ids  names  percents grades
a  101  Alice      78.5      C
b  102   John      87.5      B
c  103   Mark      68.0      D
d  104  Carol      91.5      A

In [200]:
df

ids  names  percents grades  col1  col2
a  101  Alice      78.5      C     1     0
b  102   John      87.5      B     1     1
c  103   Mark      68.0      D     1     2
d  104  Carol      91.5      A     1     3

In [201]:
df.drop(['col1', 'col2'], axis=1, inplace=True)

In [202]:
df

ids  names  percents grades
a  101  Alice      78.5      C
b  102   John      87.5      B
c  103   Mark      68.0      D
d  104  Carol      91.5      A

In [203]:
del df['grades']

In [204]:
df

ids  names  percents
a  101  Alice      78.5
b  102   John      87.5
c  103   Mark      68.0
d  104  Carol      91.5